version: '3'
services:
  #PHP Service
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./sources/:/var/www/html
      - ./docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on: 
      - mysql

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "9000:80"
    volumes:
      - ./sources/:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on: 
      - app
  #MySQL Service
  mysql:
    image: mysql:latest
    restart: unless-stopped
    hostname: dbdata
    ports:
      - "4306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    env_file:
      - ./docker/env/.env_mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local